### ISSUE TITLE
Are you able to provide teams_map.csv?

### ISSUE THREAD

**Issue by priyen** [Egiob/csgo_forecasting#1]
Hey, cool project! I'm trying to play around with it but need a teams_map.csv, can you provide it or let me know where you got it? 

Also, this appears to be missing: No such file or directory: 'var/model_update_history'

Thanks for the help!

**Comment by Egiob** [comment]
Done ! It is just a fille that normalize names so that "virtus.pro" and "vp" and "virtus pro" are understood as a same team .
Don't hesitate if you have more questions !

**Comment by priyen** [comment]
Hey @Egiob, did you add it? I still just see the git ignore file in the repo. Also are you able to add 'var/model_update_history'?

**Comment by Egiob** [comment]
Yes check again ;)

**Comment by priyen** [comment]
@Egiob  I see teams map now thanks! What about update_model_history?

**Comment by Egiob** [comment]
Good point, they were not supposed to be used anymore, i removed every access to them in the view.py.
