### ISSUE TITLE
Running the Django application

### ISSUE THREAD

**Issue by krazzarkov** [Egiob/csgo_forecasting#2]
Hello,

I was taking a look at your project and it seems super cool. I wanted to test it out and see if I could experiment with it however I am having some issues getting it to run.

I have anaconda installed and created an environment using the requirments.txt. However, I am still having a hard time figuring out how to start the Django app. 

I've worked with Django before however, I am still quite new to it. I noticed that your application does not have a manage.py file so I wasn't sure what the proper procedure is to get it to run.

Any help would be greatly appreciated :)

**Comment by krazzarkov** [comment]
**Update:**

I created a manage.py file outside the paris and mysite folder and got it to work.

![image](https://user-images.githubusercontent.com/8461672/103494607-8392f900-4dec-11eb-8f37-4efe81407fce.png)


My issue now is that I am unable to populate the database with the module_scrapping.py tool.

when I run the command `python module_scrapping.py` I get the following error:

![image](https://user-images.githubusercontent.com/8461672/103494619-8ee62480-4dec-11eb-8c67-a18cb6f083e5.png)

I suspected that it was a configuration issue so I tried using the command `export DJANGO_SETTINGS_MODULE=mysite.settings` and ran `python module_scrapping.py`  however it tells me that there is no module named "mysite". 

I'm guessing that I am doing something wrong however my limited experience with Django is leaving me stuck even after extensive troubleshooting. Let me know if you have any tips.

**Comment by Egiob** [comment]
Hello, thanks for your feedback !
You are right the manage.py was missing. To populate the db i recommand you use the notebooks auto_betting_simu.ipynb and populate_db.ipynb. The first scraps in real time the upcoming and recently finished matches and the second scraps recursively ancient matches on the site. Let me know if this works. I added a couple of recommandations at the end of the readme, it may be useful for you !

**Comment by krazzarkov** [comment]
Hi @Egiob,

Thank you for getting back to me and updating the repository.

I redownloaded the code and attempted to populate the database with the notebooks. I followed your instructions and managed to get to the point where I try and run the notebooks. 

Unfortunately, I am still running into some issues with the scrapper as I am getting an error with Chrome and the ChromeDriver. I have attached screenshots of my error below:

Error for **populate_db**:

![image](https://user-images.githubusercontent.com/8461672/103831731-8f233180-5031-11eb-9313-7a4792d8026a.png)

Error for **auto_betting_simu**:

![image](https://user-images.githubusercontent.com/8461672/103831774-a530f200-5031-11eb-99ab-a9315b72d044.png)

Both of these errors are quite similar and I spent a decent amount of time trying to debug and figure out the issue. My chrome is installed inside the /usr/bin/google-chrome as well as my chromedriver. 

I also checked for compatibility between chromedriver and my google chrome versions and it seemed to be okay as they were on the same version:

![image](https://user-images.githubusercontent.com/8461672/103831923-ffca4e00-5031-11eb-8f9b-198f68cd4126.png)

I also looked online and found recommendations to use parameters such as no-sandbox, disable-extensions, and headless which I tried adding to paris/utils.py however that did not fix my issue as well.

I'm not entirely sure where this error is coming from. I considered it might have something to do with the fact that I am running this project on WSL Ubuntu 18.04 on my Windows PC however I am not quite sure. 

If you have any tips or recommendations on what I can try doing I would greatly appreciate it!

Thank you for your time :)

**Comment by Egiob** [comment]
Hey ! 
It is clearly a Selenium/Chrome problem, i guess that you can fix it by setting good options when instantiating the chrome driver with selenium. See https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t. 
I added this option since it changes nothing for me and it could solve your problem :
```
options.add_argument("--disable-dev-shm-usage")
```
Let me know if it works for you !

**Comment by krazzarkov** [comment]
Hi @Egiob,

Thank you for the fast reply and sorry in advance for the long post!

I tried running your updated code with `options.add_argument("--disable-dev-shm-usage")` however unfortunately that didn't work. After doing some more research, I came to the conclusion that the errors were likely coming from the fact that I was using WSL to run the project. 

After figuring this out, I scrapped everything and switched to working with Anaconda on Windows. After some troubleshooting, I was able to get almost everything working including the chromedriver.

The only issue that I came across was that even on Windows when I ran `auto_betting_simu` and `populate_db` it was telling me that it could not find my chromedriver when I had installed it correctly to my windows system path and was able to type "chromedriver" in my cmd prompt and get it to execute. 

I fixed this by adding this line to utils.py and module_scrapping.py:
 `self.driver = webdriver.Chrome('C:\webdrivers\chromedriver.exe', options = options) `

Obviously, this isn't the best solution but I decided to leave it for now. 

I am now able to run both `auto_betting_simu` and `populate_db` on Jupyter and get chrome to open. However, I am still having some issues.

With the `auto_betting_simu` notebook, running it gives me the following error:

![image](https://user-images.githubusercontent.com/8461672/103958896-2310fe00-5103-11eb-9d86-c02b89c40cdc.png)

It seems to be looking for `history.db` but it cannot find it as the file doesn't exist. 

I already ran `python manage.py migrate --run-syncdb` so I'm assuming the file is just missing.

My second issue technically occurs on both `auto_betting_simu` and `populate_db` where when chrome launches it heads to csgolounge.com (I already signed into it previously) and cannot get past the CloudFlare checking browser page. I was looking at the window and it seemed to be refreshing around every 3-4 seconds. I am not sure if the refreshing is the issue however on my end I am unable to get past the checking browser page of csgolounge. 

![image](https://user-images.githubusercontent.com/8461672/103959257-104af900-5104-11eb-9fdc-a6084bbd4b21.png)

![image](https://user-images.githubusercontent.com/8461672/103959275-17720700-5104-11eb-9289-1aed8e4018c9.png)

Once again, any help would be greatly appreciated. With every day it seems that I slowly get closer to getting the project to work on my end! Thank you :)

**Comment by Egiob** [comment]
Hey ! It's strange, the history.db file seems to be present in the repo. I re-downloaded the repo in a clean environment and tried it myself, it worked just fine with the history.db file. For the CloudFare protection, sometimes i have to manually load the page in the driver-controlled browser, but after that, it recognizes the browser and i don't have problems anymore. Don't know if i was useful here. Let me know if i can do anything else ! (BTW i have chrome version 85, don't know if this version could explain why it works for me and not for you)

**Comment by krazzarkov** [comment]
Hi @Egiob,

Had some more progress today.

I managed to get past the Cloudflare screen. I'm still not entirely sure what I did as I didn't change much in terms of code. 

I was having the same issues as yesterday where the CSGOLounge Cloudflare screen would be displayed and would refresh randomly for an infinite amount of time. The problem was that I was unable to login to CSGOLounge with the driver-controlled browser as even if I made a new tab and navigated to CSGOLounge manually, it would still get stuck on the Cloudflare screen. At the time I was experimenting with using a VPN and I believe that while the driver-controlled browser was still open I turned off my VPN and if I remember correctly for some reason that allowed me to get into CSGOLounge successfully. After doing that once, it seemed that the website remembered me, and from there I was able to get past Cloudflare every time I ran the notebooks. 

Also as a note, I removed the incognito argument from `module_scrapping.py` as I was still having issues with Cloudflare for one of the notebooks, and removing the argument fixed it. 

Unfortunately, even though Cloudflare works I am still having some issues. 

In your previous message you told me that history.db exists in the repository and you are right. Even though I looked for it yesterday I guess I was just tired and didn't notice it. I do in fact have it in my /var/ folder. 

The problem I am having now is that both the `populate_db` and `auto_betting_simu` are unable to access files in the /var/ folder as seen below:

![image](https://user-images.githubusercontent.com/8461672/104072862-2c60a000-51c1-11eb-90ab-2cbf2489eaa9.png)

![image](https://user-images.githubusercontent.com/8461672/104072930-51eda980-51c1-11eb-82bf-8f69a975fe08.png)

I've tried editing the DATA_DIR variable and using different path methods such as using double slashes `\\`, using `os.path.join`, using Path from pathlib, and also using my entire absolute path as well with none of those methods working. 

I actually had a similar issue earlier inside the `auto_betting_simu` notebook with `clf = joblib.load` and fixed that by using my absolute path as seen below:

![image](https://user-images.githubusercontent.com/8461672/104073272-199a9b00-51c2-11eb-8123-7e508c3290c4.png)

I'll keep trying to fix this, but if you have any tips or suggestions on what I can try that would be greatly appreciated. I am currently running this on Windows and using my environment inside Anaconda to run the notebooks. 

Thank you for all your help.

**Comment by krazzarkov** [comment]
Good news @Egiob

I got it to work! I think my symlinks were broken on the old repository so I re-cloned the repo and it immediately worked without having to change my file paths.

I ran both the `auto_betting_simu` and `populate_db` and they seemed to work with no errors. Now that the project works I can finally play around with it and learn more about it.

I did have some questions I was hoping you can answer as there were parts of the project that confused me.

1. When running the `auto_betting_simu` notebook, it tells me that some teams were not found. I am guessing this is because most of the teams that are currently playing this month are brand new and do not exist. My question is, how does the project find the team names and update them when more teams are added? Is this feature based on the `feature_engineering` notebook that uses PandaScore?

![image](https://user-images.githubusercontent.com/8461672/104079542-81f47700-51d8-11eb-91e4-4a12cc2fcab5.png)

2.  I was also a little confused about the way that the Django website shows the odds. On the screenshot below, the odds displayed in red are the calculated predictions generated by the project and the odds displayed in grey are obviously the CSGOLounge odds, correct? I am asking as if the red values are the calculated predictions, for the example below, they seem to be very different compared to the bookmaker odds so I was curious if this is normal or an issue on my end.

![image](https://user-images.githubusercontent.com/8461672/104079641-034c0980-51d9-11eb-9aee-bc1ec1e32894.png)

3. When running the feature_engineering notebook, I came across some weird behavior and bugs. The odd part is that the notebook still ran in the beginning and updated the `history.db` file from 12kb to 1256kb. However, I got some weird messages and even an error towards the end. Perhaps it could be an issue with my TensorFlow version?

![image](https://user-images.githubusercontent.com/8461672/104080117-16f86f80-51db-11eb-979b-f5e9d11dbc8d.png)

![image](https://user-images.githubusercontent.com/8461672/104080086-edd7df00-51da-11eb-8ec3-eba93f96e0f1.png)

![image](https://user-images.githubusercontent.com/8461672/104080090-f3352980-51da-11eb-8931-d230ea1005b4.png)

I suspect that for the project to work properly the `feature_engineering` notebook needs to run correctly without errors. Please let me know if the Tensorflow depreciation messages and the "None" being spammed for `update_history(token)` is normal behavior and if you have any suggestions on what could be causing the ValueError in the last screenshot.

Again, thank you for all your help!

**Comment by Egiob** [comment]
Hello ! You're damn right for the displayed odds, they were added in the wrong order (shame on me). You may want to pull, flush your db.sqlite file and start scrapping again. 

- For the tensorflow thing, in fact what is at the end of the feature_engineering notebook is not really supposed to be used (after title 2.1), it is old thing that i have done a while ago. I don't think that a complex neural network model will perform better at predicting the odds than a more classical one such as logistic regression. See the notebook strategy_analysis. Anyway if you want to try things, it's up to you.

- For the teams missing and for good predictions, you may want to periodically (once in a week for instance) update elo, team ranking and history (see args of the class FeaturesBuilder init). If the team is missing it also may be a problem of alias because the PandaScore api and csgolounge have often slighlty different names. In teams_map.csv, i put an new alias each time i see one (for example virtus pro is often referred as 'v.p' or 'virtus.pro')

Anyway thanks for the feedback ! If you appreciate the project and you want to improve it, don't hesitate to make pull request or just propose improvements. And if you want to go further in applying this to real bets we can discuss it in private ;)

**Comment by krazzarkov** [comment]
Hi @Egiob,

Thanks for getting back to me. I was busy today but tomorrow I'll try pulling and scrapping again. 

If you want you can add me on discord: Kraz#7145 or if you prefer a different platform you can let me know as well. 

Once again, thank you for all your help!
