### ISSUE TITLE
Delete Bet if auto_betting_simu determines it's not a good bet

### ISSUE THREAD

**Issue by krazzarkov** [Egiob/csgo_forecasting#3]
Hi @Egiob  ,

I finally had some time to play around with the project.

I've been trying to go through all the code and understand how it works and operates. My plan is to do an experiment and set up the project on a server and see how profitable the algorithm is after three months.

I've run the project for about a day now and have been monitoring the bets and predictions and noticed something strange which I was hoping you could clarify. 

![image](https://user-images.githubusercontent.com/8461672/104381452-4eb82d80-54e1-11eb-91b9-21702d23f4fa.png)

In the screenshot above the left side represents one iteration and the right side represents an iteration ran 30 seconds after the one on the left. 

The way I understand it is that on the left the algorithm determined that it should place a bet with the current information it had, and on the right, as the odds updated, it determined that the bet was not worth it. 

The problem is that after checking the Django admin page for bets, the auto_betting_simu had not deleted the EV and Kelly strategy bets of 0.41 and 1 which it had placed before. 

My question is if this is intended behavior or if it is just a feature that has not been implemented yet. Obviously, the Naive strategy will always place a bet no matter what however, if the notebook determines that it is not a good bet should it not delete any bets that have already been placed for that match?

**Comment by krazzarkov** [comment]
I was looking over the code changes and it seems like this issue was fixed. The notebook now bets $0 if the bet is determined to be bad. 

Thank you guys

**Comment by Egiob** [comment]
Hey ! I didn't see you message at time, but i did several improvements these days :) I found out that many things were not working as expected and fixed it.
